- hosts: all
  become: true
  gather_facts: yes


  vars:
      users:
        - alex
        - aravind
        - david
        - philipp
      beats:
        - filebeat
        - heartbeat
        - metricbeat
        - packetbeat


  vars_files:
    - .config.yml


  tasks:

    # System
    - name: Update and upgrade apt packages
      apt: upgrade=dist force_apt_get=yes update_cache=yes

    - name: Install NTP to avoid time drift and PIP to manage Python dependencies plus its build tools
      apt:
        name: [ 'ntp', 'ntpdate', 'python3-pip', 'build-essential', 'libssl-dev', 'libffi-dev', 'whois' ]

    - name: Install the pyOpenSSL library, so Ansible can use it to check TLS certificates
      pip: name=pyopenssl

    - name: Install the JDK
      apt: name=openjdk-17-jdk-headless install_recommends=no

    - name: Install Gradle
      apt: name=gradle


    # Add users
    - name: Add a group for developers
      group:
        name: developers
        state: present

    - name: Add users
      user:
        name: "{{ item }}"
        groups:
          - sudo
          - developers
        shell: /bin/bash
        state: present
      loop: "{{ users }}"

    - name: Placing the public SSH keys for the users
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', './ansible/' + item + '.pub') }}"
      loop: "{{ users }}"


    # SSH
    - name: Allow passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Allow our users to log in via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowUsers'
        line: "AllowUsers ubuntu {{ users|join(' ') }}"
        state: present

    - name: Restart SSH
      service: name=ssh state=restarted


    # App privileges for Elasticsearch
    - name: Create the Elasticsearch role for the app
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{elasticsearch_host}}/_security/role/{{ springboot_user }}-role"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        body:
          cluster:
            - monitor
          indices:
            - names:
                - products
              privileges:
                - all
        status_code:
          - 200
          - 201

    - name: Create the Elasticsearch user for the app
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{elasticsearch_host}}/_security/user/{{ springboot_user }}"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        body:
          password: "{{ springboot_password }}"
          roles:
            - "{{ springboot_user }}-role"
        status_code:
          - 200
          - 201


    # Agent
    - name: Uninstall elastic-agent if there is a previous installation (will fail if there isn't)
      command: "elastic-agent uninstall -f"
      ignore_errors: true

    - name: Purge elastic-agent to always start fresh
      apt: name=elastic-agent state=absent purge=yes

    - name: Get the elastic-agent
      apt:
        deb=https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_version }}-amd64.deb force_apt_get=yes

    - name: Get the default policy from fleet
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{kibana_host}}/api/fleet/agent_policies?kuery=name%20%3A%20%22Default%20policy%22"
        method: GET
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        status_code:
          - 200
      register: fleet_policy

    - name: Create an enrollment_token from Kibana for elastic-agent (will fail if it already exists)
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{kibana_host}}/api/fleet/enrollment-api-keys"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        headers:
          kbn-xsrf: fleet
        body:
          name: "{{ inventory_hostname }}"
          policy_id: "{{ fleet_policy.json['items'][0].id }}" #Workaround for special meaning of "items" in Ansible 🤬
      ignore_errors: true

    - name: Get the enrollment_token from Kibana for elastic-agent
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{kibana_host}}/api/fleet/enrollment-api-keys?kuery=name%20%3A%20{{ inventory_hostname }}*"
        method: GET
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        status_code:
          - 200
      register: fleet_token

    # TODO once we have the fleet_host, we don't need the replace hack for apm_host any more
    - name: Enroll the elastic-agent and force it to overwrite any previous config
      command: elastic-agent enroll --url="https://{{ cloud_alias }}.fleet.{{ apm_host.split('.')[2:4]|join('.') }}.found.io:443" --enrollment-token={{ fleet_token.json.list[0].api_key }} --force

    - name: Restart and make sure the elastic-agent autostarts
      service: name=elastic-agent state=restarted enabled=yes


    # Beats
    - name: Create the Elasticsearch role for Beats
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{elasticsearch_host}}/_security/role/{{ beats_user }}-role"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        body:
          cluster:
            - monitor
            - manage #Could be more fine grained if we split up installation and data collection
          indices:
            - names:
                - "*beat-*"
                - "logs-*"
                - "metrics-*"
              privileges:
                - all
          applications:
            - application: kibana-.kibana
              privileges:
                - feature_indexPatterns.all
                - feature_savedObjectsManagement.all
                - feature_advancedSettings.all
                - feature_actions.all
                - feature_savedObjectsTagging.all
                - feature_fleet.all
                - feature_stackAlerts.all
              resources:
                - '*'
        status_code:
          - 200
          - 201

    - name: Create the Elasticsearch user for Beats
      delegate_to: 127.0.0.1
      become: false
      uri:
        url: "{{elasticsearch_host}}/_security/user/{{ beats_user }}"
        body_format: json
        method: POST
        user: "{{ elasticsearch_user }}"
        password: "{{ elasticsearch_password }}"
        force_basic_auth: true
        body:
          password: "{{ beats_password }}"
          roles:
            - "{{ beats_user }}-role"
            - filebeat_setup
            - kibana_admin
            - ingest_admin
            - beats_admin
            - machine_learning_admin
        status_code:
          - 200
          - 201

    - name: Get the Beats
      apt: deb=https://artifacts.elastic.co/downloads/beats/{{ item }}/{{ item }}-{{ elastic_version }}-amd64.deb force_apt_get=yes
      loop: "{{ beats }}"

    - name: Change the Beats configuration
      template: "src=ansible/{{ item }}.yml dest=/etc/{{ item }}/{{ item }}.yml"
      loop: "{{ beats }}"

    - name: Create the Beats keystores
      command: "{{ item }} keystore create --force"
      loop: "{{ beats }}"

    - name: Set the Elasticsearch password for Beats
      lineinfile:
        dest: /tmp/cred
        line: "{{ beats_password }}"
        state: present
        create: true
        mode: 0600

    - name: Set the password in the Beats keystore files
      shell: cat /tmp/cred | {{ item }} keystore add ES_PWD --stdin --force
      loop: "{{ beats }}"

    - name: Remove the password file
      file:
        path: /tmp/cred
        state: absent

    - name: Run the setup for all the beats (except Heartbeat — not needed)
      shell: "{{ item }} setup"
      loop:
      - filebeat
      - metricbeat
      - packetbeat

    - name: Restart and make sure the Beats autostart
      service: name={{ item }} state=restarted enabled=yes
      loop:
      - filebeat
      - heartbeat-elastic #Different name, can't use the default list
      - metricbeat
      - packetbeat


    # nginx
    - name: Install nginx
      apt: name=nginx force_apt_get=yes

    - name: Stop nginx so that Certbot can bind to port 80
      service: name=nginx state=stopped

    - name: Install certbot
      apt: name=python3-certbot-nginx

    - name: Add domains to the certificate
      set_fact:
        certificates:
          - "{{ inventory_hostname }}"
          - "{{ domain }}"
          - "www.{{ domain }}"

    - name: Create the certificate
      command: >
        certbot certonly --non-interactive --standalone
        --agree-tos --email admin@{{ domain }}
        -d {{ certificates | join(',') }}
        creates=/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem

    - name: Add crontab to renew certificates every second month on Sunday night
      cron:
        name: Renew Let's Encrypt certificate
        minute: "30"
        hour: "3"
        weekday: "0"
        month: "*/2"
        job: service nginx stop && certbot renew >> /var/log/letsencrypt/renew.log && service nginx start

    - name: Generate strong dhparams, but only if the file doesn't exist
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 creates=/etc/ssl/certs/dhparam.pem

    - name: Set a global TLS configuration
      template: src=ansible/tls.conf dest=/etc/nginx/tls.conf

    - name: Change the nginx configuration
      template: src=ansible/nginx.conf dest=/etc/nginx/sites-available/default

    - name: Restart nginx and make sure it autostarts
      service: name=nginx state=restarted enabled=yes

    - name: Check HTTP
      delegate_to: 127.0.0.1
      become: false
      retries: 3
      delay: 2
      uri:
        url: "http://{{ inventory_hostname }}"
        follow_redirects: none
        status_code: 301
      register: response

    - name: Fail if HTTP is not being redirected to HTTPS
      fail:
      when: response.status != 301

    - name: Check HTTPS
      openssl_certificate:
        path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
        provider: assertonly
        subject_alt_name:
          - "DNS:{{ inventory_hostname }}"
          - "DNS:{{ domain }}"
