metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - core
    - diskio
    - filesystem
    - fsstat
    - memory
    - network
    - process
    - process_summary
    - socket
  enabled: true
  period: 10s
  processes: ['.*']
  cgroups: true
  process.include_top_n:
    enabled: true
    by_cpu: 20
    by_memory: 20
- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["localhost:8080/actuator/prometheus"]
  metrics_path: /metrics

name: "{{ inventory_hostname }}"


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ beats_user }}"
  password: "{{ beats_password }}" #"${ES_PWD}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ beats_user }}"
    password: "{{ beats_password }}" #"${ES_PWD}"
  ilm.overwrite: true


#cloud.id: ""
#cloud.auth: "{{ beats_user }}:${ES_PWD}"
